// scripts/generate-milb-map.ts
import fs from 'fs';
import path from 'path';

async function generateMiLBMap() {
  console.log("⚾ Fetching MLB and MiLB Team data...");

  try {
    // 1. Fetch all Major League Teams (sportId=1) to get their abbreviations (e.g., "LAD", "NYY")
    const mlbRes = await fetch("https://statsapi.mlb.com/api/v1/teams?sportId=1");
    const mlbData = await mlbRes.json();
    
    const mlbAbbrevMap: Record<number, string> = {};
    for (const team of mlbData.teams) {
      mlbAbbrevMap[team.id] = team.abbreviation;
    }

    // 2. Fetch all Minor League Teams (sportIds 11=AAA, 12=AA, 13=A+, 14=A, 16=Rookie)
    const milbRes = await fetch("https://statsapi.mlb.com/api/v1/teams?sportIds=11,12,13,14,16");
    const milbData = await milbRes.json();

    const milbMap: Record<number, { name: string, parentAbbrev: string, parentName: string }> = {};

    for (const team of milbData.teams) {
      // If the minor league team has a declared MLB parent
      if (team.parentOrgId && team.parentOrgName) {
        milbMap[team.id] = {
          name: team.name,
          parentName: team.parentOrgName,
          parentAbbrev: mlbAbbrevMap[team.parentOrgId] || "???"
        };
      }
    }

    // 3. Generate the TypeScript file content
    const fileContent = `// Automatically generated by scripts/generate-milb-map.ts
// Do not edit manually.

export const MILB_PARENT_MAP: Record<number, { name: string, parentAbbrev: string, parentName: string }> = ${JSON.stringify(milbMap, null, 2)};
`;

    // 4. Save it to our lib folder
    const outputPath = path.join(process.cwd(), 'src', 'lib', 'milb-map.ts');
    fs.writeFileSync(outputPath, fileContent);

    console.log(`✅ Successfully mapped ${Object.keys(milbMap).length} Minor League teams!`);
    console.log(`📁 File saved to: src/lib/milb-map.ts`);

  } catch (error) {
    console.error("🚨 Failed to generate MiLB map:", error);
  }
}

generateMiLBMap();