// Automatically generated by scripts/generate-milb-map.ts
// Do not edit manually.

export const MILB_PARENT_MAP: Record<number, { name: string, parentAbbrev: string, parentName: string }> = {
  "102": {
    "name": "Round Rock Express",
    "parentName": "Texas Rangers",
    "parentAbbrev": "TEX"
  },
  "103": {
    "name": "Lake Elsinore Storm",
    "parentName": "San Diego Padres",
    "parentAbbrev": "SD"
  },
  "105": {
    "name": "Sacramento River Cats",
    "parentName": "San Francisco Giants",
    "parentAbbrev": "SF"
  },
  "106": {
    "name": "Erie SeaWolves",
    "parentName": "Detroit Tigers",
    "parentAbbrev": "DET"
  },
  "233": {
    "name": "Charleston RiverDogs",
    "parentName": "Tampa Bay Rays",
    "parentAbbrev": "TB"
  },
  "234": {
    "name": "Durham Bulls",
    "parentName": "Tampa Bay Rays",
    "parentAbbrev": "TB"
  },
  "235": {
    "name": "Memphis Redbirds",
    "parentName": "St. Louis Cardinals",
    "parentAbbrev": "STL"
  },
  "237": {
    "name": "Midland RockHounds",
    "parentName": "Athletics",
    "parentAbbrev": "ATH"
  },
  "238": {
    "name": "Oklahoma City Comets",
    "parentName": "Los Angeles Dodgers",
    "parentAbbrev": "LAD"
  },
  "247": {
    "name": "Birmingham Barons",
    "parentName": "Chicago White Sox",
    "parentAbbrev": "CWS"
  },
  "249": {
    "name": "Wilson Warbirds",
    "parentName": "Milwaukee Brewers",
    "parentAbbrev": "MIL"
  },
  "259": {
    "name": "Fresno Grizzlies",
    "parentName": "Colorado Rockies",
    "parentAbbrev": "COL"
  },
  "260": {
    "name": "Tulsa Drillers",
    "parentName": "Los Angeles Dodgers",
    "parentAbbrev": "LAD"
  },
  "279": {
    "name": "Palm Beach Cardinals",
    "parentName": "St. Louis Cardinals",
    "parentAbbrev": "STL"
  },
  "342": {
    "name": "Albuquerque Isotopes",
    "parentName": "Colorado Rockies",
    "parentAbbrev": "COL"
  },
  "400": {
    "name": "Las Vegas Aviators",
    "parentName": "Athletics",
    "parentAbbrev": "ATH"
  },
  "401": {
    "name": "Inland Empire 66ers",
    "parentName": "Seattle Mariners",
    "parentAbbrev": "SEA"
  },
  "402": {
    "name": "Akron RubberDucks",
    "parentName": "Cleveland Guardians",
    "parentAbbrev": "CLE"
  },
  "403": {
    "name": "Everett AquaSox",
    "parentName": "Seattle Mariners",
    "parentAbbrev": "SEA"
  },
  "404": {
    "name": "ACL Angels",
    "parentName": "Los Angeles Angels",
    "parentAbbrev": "LAA"
  },
  "406": {
    "name": "ACL Brewers",
    "parentName": "Milwaukee Brewers",
    "parentAbbrev": "MIL"
  },
  "407": {
    "name": "ACL Cubs",
    "parentName": "Chicago Cubs",
    "parentAbbrev": "CHC"
  },
  "408": {
    "name": "ACL Giants",
    "parentName": "San Francisco Giants",
    "parentAbbrev": "SF"
  },
  "409": {
    "name": "ACL Mariners",
    "parentName": "Seattle Mariners",
    "parentAbbrev": "SEA"
  },
  "410": {
    "name": "ACL Padres",
    "parentName": "San Diego Padres",
    "parentAbbrev": "SD"
  },
  "411": {
    "name": "ACL Rangers",
    "parentName": "Texas Rangers",
    "parentAbbrev": "TEX"
  },
  "412": {
    "name": "ACL Royals",
    "parentName": "Kansas City Royals",
    "parentAbbrev": "KC"
  },
  "414": {
    "name": "Salem RidgeYaks",
    "parentName": "Boston Red Sox",
    "parentAbbrev": "BOS"
  },
  "416": {
    "name": "Louisville Bats",
    "parentName": "Cincinnati Reds",
    "parentAbbrev": "CIN"
  },
  "418": {
    "name": "Chesapeake Baysox",
    "parentName": "Baltimore Orioles",
    "parentAbbrev": "BAL"
  },
  "419": {
    "name": "Hillsboro Hops",
    "parentName": "Arizona Diamondbacks",
    "parentAbbrev": "AZ"
  },
  "421": {
    "name": "Montgomery Biscuits",
    "parentName": "Tampa Bay Rays",
    "parentAbbrev": "TB"
  },
  "422": {
    "name": "Buffalo Bisons",
    "parentName": "Toronto Blue Jays",
    "parentAbbrev": "TOR"
  },
  "424": {
    "name": "Dunedin Blue Jays",
    "parentName": "Toronto Blue Jays",
    "parentAbbrev": "TOR"
  },
  "426": {
    "name": "Wilmington Blue Rocks",
    "parentName": "Washington Nationals",
    "parentAbbrev": "WSH"
  },
  "427": {
    "name": "Jersey Shore BlueClaws",
    "parentName": "Philadelphia Phillies",
    "parentAbbrev": "PHI"
  },
  "428": {
    "name": "Greenville Drive",
    "parentName": "Boston Red Sox",
    "parentAbbrev": "BOS"
  },
  "431": {
    "name": "Gwinnett Stripers",
    "parentName": "Atlanta Braves",
    "parentAbbrev": "ATL"
  },
  "432": {
    "name": "Rome Emperors",
    "parentName": "Atlanta Braves",
    "parentAbbrev": "ATL"
  },
  "435": {
    "name": "Vancouver Canadians",
    "parentName": "Toronto Blue Jays",
    "parentAbbrev": "TOR"
  },
  "436": {
    "name": "Fredericksburg Nationals",
    "parentName": "Washington Nationals",
    "parentAbbrev": "WSH"
  },
  "437": {
    "name": "Lake County Captains",
    "parentName": "Cleveland Guardians",
    "parentAbbrev": "CLE"
  },
  "440": {
    "name": "Springfield Cardinals",
    "parentName": "St. Louis Cardinals",
    "parentAbbrev": "STL"
  },
  "443": {
    "name": "Peoria Chiefs",
    "parentName": "St. Louis Cardinals",
    "parentAbbrev": "STL"
  },
  "445": {
    "name": "Columbus Clippers",
    "parentName": "Cleveland Guardians",
    "parentAbbrev": "CLE"
  },
  "448": {
    "name": "Hickory Crawdads",
    "parentName": "Texas Rangers",
    "parentAbbrev": "TEX"
  },
  "450": {
    "name": "Daytona Tortugas",
    "parentName": "Cincinnati Reds",
    "parentAbbrev": "CIN"
  },
  "451": {
    "name": "Iowa Cubs",
    "parentName": "Chicago Cubs",
    "parentAbbrev": "CHC"
  },
  "452": {
    "name": "Altoona Curve",
    "parentName": "Pittsburgh Pirates",
    "parentAbbrev": "PIT"
  },
  "453": {
    "name": "Brooklyn Cyclones",
    "parentName": "New York Mets",
    "parentAbbrev": "NYM"
  },
  "456": {
    "name": "Great Lakes Loons",
    "parentName": "Los Angeles Dodgers",
    "parentAbbrev": "LAD"
  },
  "459": {
    "name": "Dayton Dragons",
    "parentName": "Cincinnati Reds",
    "parentAbbrev": "CIN"
  },
  "460": {
    "name": "Tri-City Dust Devils",
    "parentName": "Los Angeles Angels",
    "parentAbbrev": "LAA"
  },
  "461": {
    "name": "Eugene Emeralds",
    "parentName": "San Francisco Giants",
    "parentAbbrev": "SF"
  },
  "463": {
    "name": "New Hampshire Fisher Cats",
    "parentName": "Toronto Blue Jays",
    "parentAbbrev": "TOR"
  },
  "464": {
    "name": "FCL Braves",
    "parentName": "Atlanta Braves",
    "parentAbbrev": "ATL"
  },
  "466": {
    "name": "FCL Nationals",
    "parentName": "Washington Nationals",
    "parentAbbrev": "WSH"
  },
  "467": {
    "name": "FCL Marlins",
    "parentName": "Miami Marlins",
    "parentAbbrev": "MIA"
  },
  "468": {
    "name": "FCL Mets",
    "parentName": "New York Mets",
    "parentAbbrev": "NYM"
  },
  "469": {
    "name": "FCL Phillies",
    "parentName": "Philadelphia Phillies",
    "parentAbbrev": "PHI"
  },
  "470": {
    "name": "FCL Pirates",
    "parentName": "Pittsburgh Pirates",
    "parentAbbrev": "PIT"
  },
  "471": {
    "name": "FCL Red Sox",
    "parentName": "Boston Red Sox",
    "parentAbbrev": "BOS"
  },
  "473": {
    "name": "FCL Tigers",
    "parentName": "Detroit Tigers",
    "parentAbbrev": "DET"
  },
  "474": {
    "name": "FCL Twins",
    "parentName": "Minnesota Twins",
    "parentAbbrev": "MIN"
  },
  "475": {
    "name": "FCL Yankees",
    "parentName": "New York Yankees",
    "parentAbbrev": "NYY"
  },
  "476": {
    "name": "San Jose Giants",
    "parentName": "San Francisco Giants",
    "parentAbbrev": "SF"
  },
  "477": {
    "name": "Greensboro Grasshoppers",
    "parentName": "Pittsburgh Pirates",
    "parentAbbrev": "PIT"
  },
  "478": {
    "name": "Augusta GreenJackets",
    "parentName": "Atlanta Braves",
    "parentAbbrev": "ATL"
  },
  "479": {
    "name": "Jupiter Hammerheads",
    "parentName": "Miami Marlins",
    "parentAbbrev": "MIA"
  },
  "481": {
    "name": "Hill City Howlers",
    "parentName": "Cleveland Guardians",
    "parentAbbrev": "CLE"
  },
  "482": {
    "name": "Corpus Christi Hooks",
    "parentName": "Houston Astros",
    "parentAbbrev": "HOU"
  },
  "484": {
    "name": "Indianapolis Indians",
    "parentName": "Pittsburgh Pirates",
    "parentAbbrev": "PIT"
  },
  "486": {
    "name": "Spokane Indians",
    "parentName": "Colorado Rockies",
    "parentAbbrev": "COL"
  },
  "487": {
    "name": "Kannapolis Cannon Ballers",
    "parentName": "Chicago White Sox",
    "parentAbbrev": "CWS"
  },
  "492": {
    "name": "Cedar Rapids Kernels",
    "parentName": "Minnesota Twins",
    "parentAbbrev": "MIN"
  },
  "493": {
    "name": "Frederick Keys",
    "parentName": "Baltimore Orioles",
    "parentAbbrev": "BAL"
  },
  "494": {
    "name": "Charlotte Knights",
    "parentName": "Chicago White Sox",
    "parentAbbrev": "CWS"
  },
  "498": {
    "name": "Chattanooga Lookouts",
    "parentName": "Cincinnati Reds",
    "parentAbbrev": "CIN"
  },
  "499": {
    "name": "Lansing Lugnuts",
    "parentName": "Athletics",
    "parentAbbrev": "ATH"
  },
  "505": {
    "name": "Binghamton Rumble Ponies",
    "parentName": "New York Mets",
    "parentAbbrev": "NYM"
  },
  "507": {
    "name": "St. Lucie Mets",
    "parentName": "New York Mets",
    "parentAbbrev": "NYM"
  },
  "509": {
    "name": "Fort Myers Mighty Mussels",
    "parentName": "Minnesota Twins",
    "parentAbbrev": "MIN"
  },
  "510": {
    "name": "San Antonio Missions",
    "parentName": "San Diego Padres",
    "parentAbbrev": "SD"
  },
  "512": {
    "name": "Toledo Mud Hens",
    "parentName": "Detroit Tigers",
    "parentAbbrev": "DET"
  },
  "516": {
    "name": "Visalia Rawhide",
    "parentName": "Arizona Diamondbacks",
    "parentAbbrev": "AZ"
  },
  "521": {
    "name": "Myrtle Beach Pelicans",
    "parentName": "Chicago Cubs",
    "parentAbbrev": "CHC"
  },
  "522": {
    "name": "Reading Fightin Phils",
    "parentName": "Philadelphia Phillies",
    "parentAbbrev": "PHI"
  },
  "524": {
    "name": "Stockton Ports",
    "parentName": "Athletics",
    "parentAbbrev": "ATH"
  },
  "526": {
    "name": "Rancho Cucamonga Quakes",
    "parentName": "Los Angeles Angels",
    "parentAbbrev": "LAA"
  },
  "529": {
    "name": "Tacoma Rainiers",
    "parentName": "Seattle Mariners",
    "parentAbbrev": "SEA"
  },
  "531": {
    "name": "Scranton/Wilkes-Barre RailRiders",
    "parentName": "New York Yankees",
    "parentAbbrev": "NYY"
  },
  "533": {
    "name": "Worcester Red Sox",
    "parentName": "Boston Red Sox",
    "parentAbbrev": "BOS"
  },
  "534": {
    "name": "Rochester Red Wings",
    "parentName": "Washington Nationals",
    "parentAbbrev": "WSH"
  },
  "537": {
    "name": "Hudson Valley Renegades",
    "parentName": "New York Yankees",
    "parentAbbrev": "NYY"
  },
  "538": {
    "name": "Hartford Yard Goats",
    "parentName": "Colorado Rockies",
    "parentAbbrev": "COL"
  },
  "540": {
    "name": "Frisco RoughRiders",
    "parentName": "Texas Rangers",
    "parentAbbrev": "TEX"
  },
  "541": {
    "name": "Omaha Storm Chasers",
    "parentName": "Kansas City Royals",
    "parentAbbrev": "KC"
  },
  "546": {
    "name": "Portland Sea Dogs",
    "parentName": "Boston Red Sox",
    "parentAbbrev": "BOS"
  },
  "547": {
    "name": "Harrisburg Senators",
    "parentName": "Washington Nationals",
    "parentAbbrev": "WSH"
  },
  "548": {
    "name": "Delmarva Shorebirds",
    "parentName": "Baltimore Orioles",
    "parentAbbrev": "BAL"
  },
  "550": {
    "name": "South Bend Cubs",
    "parentName": "Chicago Cubs",
    "parentAbbrev": "CHC"
  },
  "552": {
    "name": "Syracuse Mets",
    "parentName": "New York Mets",
    "parentAbbrev": "NYM"
  },
  "553": {
    "name": "Knoxville Smokies",
    "parentName": "Chicago Cubs",
    "parentAbbrev": "CHC"
  },
  "554": {
    "name": "Beloit Sky Carp",
    "parentName": "Miami Marlins",
    "parentAbbrev": "MIA"
  },
  "556": {
    "name": "Nashville Sounds",
    "parentName": "Milwaukee Brewers",
    "parentAbbrev": "MIL"
  },
  "559": {
    "name": "Rocket City Trash Pandas",
    "parentName": "Los Angeles Angels",
    "parentAbbrev": "LAA"
  },
  "561": {
    "name": "Salt Lake Bees",
    "parentName": "Los Angeles Angels",
    "parentAbbrev": "LAA"
  },
  "564": {
    "name": "Jacksonville Jumbo Shrimp",
    "parentName": "Miami Marlins",
    "parentAbbrev": "MIA"
  },
  "565": {
    "name": "Quad Cities River Bandits",
    "parentName": "Kansas City Royals",
    "parentAbbrev": "KC"
  },
  "566": {
    "name": "Clearwater Threshers",
    "parentName": "Philadelphia Phillies",
    "parentAbbrev": "PHI"
  },
  "568": {
    "name": "Norfolk Tides",
    "parentName": "Baltimore Orioles",
    "parentAbbrev": "BAL"
  },
  "570": {
    "name": "Lakeland Flying Tigers",
    "parentName": "Detroit Tigers",
    "parentAbbrev": "DET"
  },
  "572": {
    "name": "Wisconsin Timber Rattlers",
    "parentName": "Milwaukee Brewers",
    "parentAbbrev": "MIL"
  },
  "573": {
    "name": "Asheville Tourists",
    "parentName": "Houston Astros",
    "parentAbbrev": "HOU"
  },
  "574": {
    "name": "Arkansas Travelers",
    "parentName": "Seattle Mariners",
    "parentAbbrev": "SEA"
  },
  "580": {
    "name": "Winston-Salem Dash",
    "parentName": "Chicago White Sox",
    "parentAbbrev": "CWS"
  },
  "582": {
    "name": "West Michigan Whitecaps",
    "parentName": "Detroit Tigers",
    "parentAbbrev": "DET"
  },
  "584": {
    "name": "Fort Wayne TinCaps",
    "parentName": "San Diego Padres",
    "parentAbbrev": "SD"
  },
  "587": {
    "name": "Tampa Tarpons",
    "parentName": "New York Yankees",
    "parentAbbrev": "NYY"
  },
  "599": {
    "name": "FCL Orioles",
    "parentName": "Baltimore Orioles",
    "parentAbbrev": "BAL"
  },
  "600": {
    "name": "DSL Angels",
    "parentName": "Los Angeles Angels",
    "parentAbbrev": "LAA"
  },
  "601": {
    "name": "DSL Astros Blue",
    "parentName": "Houston Astros",
    "parentAbbrev": "HOU"
  },
  "602": {
    "name": "DSL Athletics",
    "parentName": "Athletics",
    "parentAbbrev": "ATH"
  },
  "604": {
    "name": "DSL Blue Jays Blue",
    "parentName": "Toronto Blue Jays",
    "parentAbbrev": "TOR"
  },
  "605": {
    "name": "DSL Braves",
    "parentName": "Atlanta Braves",
    "parentAbbrev": "ATL"
  },
  "607": {
    "name": "DSL Brewers Blue",
    "parentName": "Milwaukee Brewers",
    "parentAbbrev": "MIL"
  },
  "608": {
    "name": "DSL Cardinals",
    "parentName": "St. Louis Cardinals",
    "parentAbbrev": "STL"
  },
  "609": {
    "name": "DSL Cubs Blue",
    "parentName": "Chicago Cubs",
    "parentAbbrev": "CHC"
  },
  "610": {
    "name": "DSL Arizona Black",
    "parentName": "Arizona Diamondbacks",
    "parentAbbrev": "AZ"
  },
  "611": {
    "name": "DSL LAD Bautista",
    "parentName": "Los Angeles Dodgers",
    "parentAbbrev": "LAD"
  },
  "612": {
    "name": "DSL LAD Mega",
    "parentName": "Los Angeles Dodgers",
    "parentAbbrev": "LAD"
  },
  "615": {
    "name": "DSL Giants Orange",
    "parentName": "San Francisco Giants",
    "parentAbbrev": "SF"
  },
  "616": {
    "name": "DSL CLE Mendoza",
    "parentName": "Cleveland Guardians",
    "parentAbbrev": "CLE"
  },
  "618": {
    "name": "DSL Mariners",
    "parentName": "Seattle Mariners",
    "parentAbbrev": "SEA"
  },
  "619": {
    "name": "DSL Marlins",
    "parentName": "Miami Marlins",
    "parentAbbrev": "MIA"
  },
  "620": {
    "name": "DSL Mets Blue",
    "parentName": "New York Mets",
    "parentAbbrev": "NYM"
  },
  "621": {
    "name": "DSL Orioles Black",
    "parentName": "Baltimore Orioles",
    "parentAbbrev": "BAL"
  },
  "622": {
    "name": "DSL Padres Brown",
    "parentName": "San Diego Padres",
    "parentAbbrev": "SD"
  },
  "623": {
    "name": "DSL Phillies Red",
    "parentName": "Philadelphia Phillies",
    "parentAbbrev": "PHI"
  },
  "624": {
    "name": "DSL Pirates Black",
    "parentName": "Pittsburgh Pirates",
    "parentAbbrev": "PIT"
  },
  "625": {
    "name": "DSL Rangers Blue",
    "parentName": "Texas Rangers",
    "parentAbbrev": "TEX"
  },
  "626": {
    "name": "DSL Red Sox Blue",
    "parentName": "Boston Red Sox",
    "parentAbbrev": "BOS"
  },
  "627": {
    "name": "DSL Red Sox Red",
    "parentName": "Boston Red Sox",
    "parentAbbrev": "BOS"
  },
  "628": {
    "name": "DSL Reds",
    "parentName": "Cincinnati Reds",
    "parentAbbrev": "CIN"
  },
  "629": {
    "name": "DSL Rockies",
    "parentName": "Colorado Rockies",
    "parentAbbrev": "COL"
  },
  "630": {
    "name": "DSL Royals Ventura",
    "parentName": "Kansas City Royals",
    "parentAbbrev": "KC"
  },
  "631": {
    "name": "DSL Tigers 1",
    "parentName": "Detroit Tigers",
    "parentAbbrev": "DET"
  },
  "632": {
    "name": "DSL Twins",
    "parentName": "Minnesota Twins",
    "parentAbbrev": "MIN"
  },
  "633": {
    "name": "DSL White Sox",
    "parentName": "Chicago White Sox",
    "parentAbbrev": "CWS"
  },
  "634": {
    "name": "DSL NYY Bombers",
    "parentName": "New York Yankees",
    "parentAbbrev": "NYY"
  },
  "635": {
    "name": "DSL NYY Yankees",
    "parentName": "New York Yankees",
    "parentAbbrev": "NYY"
  },
  "1270": {
    "name": "DSL Nationals",
    "parentName": "Washington Nationals",
    "parentAbbrev": "WSH"
  },
  "1350": {
    "name": "Northwest Arkansas Naturals",
    "parentName": "Kansas City Royals",
    "parentAbbrev": "KC"
  },
  "1370": {
    "name": "FCL Cardinals",
    "parentName": "St. Louis Cardinals",
    "parentAbbrev": "STL"
  },
  "1390": {
    "name": "FCL Blue Jays",
    "parentName": "Toronto Blue Jays",
    "parentAbbrev": "TOR"
  },
  "1410": {
    "name": "Lehigh Valley IronPigs",
    "parentName": "Philadelphia Phillies",
    "parentAbbrev": "PHI"
  },
  "1610": {
    "name": "DSL Blue Jays Red",
    "parentName": "Toronto Blue Jays",
    "parentAbbrev": "TOR"
  },
  "1611": {
    "name": "DSL Rays",
    "parentName": "Tampa Bay Rays",
    "parentAbbrev": "TB"
  },
  "1956": {
    "name": "Somerset Patriots",
    "parentName": "New York Yankees",
    "parentAbbrev": "NYY"
  },
  "1960": {
    "name": "St. Paul Saints",
    "parentName": "Minnesota Twins",
    "parentAbbrev": "MIN"
  },
  "1991": {
    "name": "ACL D-backs",
    "parentName": "Arizona Diamondbacks",
    "parentAbbrev": "AZ"
  },
  "1994": {
    "name": "ACL Rockies",
    "parentName": "Colorado Rockies",
    "parentAbbrev": "COL"
  },
  "1997": {
    "name": "ACL White Sox",
    "parentName": "Chicago White Sox",
    "parentAbbrev": "CWS"
  },
  "1998": {
    "name": "FCL Astros",
    "parentName": "Houston Astros",
    "parentAbbrev": "HOU"
  },
  "2003": {
    "name": "FCL Rays",
    "parentName": "Tampa Bay Rays",
    "parentAbbrev": "TB"
  },
  "2101": {
    "name": "DSL Brewers Gold",
    "parentName": "Milwaukee Brewers",
    "parentAbbrev": "MIL"
  },
  "2117": {
    "name": "DSL Mets Orange",
    "parentName": "New York Mets",
    "parentAbbrev": "NYM"
  },
  "2122": {
    "name": "DSL Padres Gold",
    "parentName": "San Diego Padres",
    "parentAbbrev": "SD"
  },
  "2127": {
    "name": "DSL Miami",
    "parentName": "Miami Marlins",
    "parentAbbrev": "MIA"
  },
  "2128": {
    "name": "DSL Royals Fortuna",
    "parentName": "Kansas City Royals",
    "parentAbbrev": "KC"
  },
  "2131": {
    "name": "DSL Colorado",
    "parentName": "Colorado Rockies",
    "parentAbbrev": "COL"
  },
  "2132": {
    "name": "DSL Tigers 2",
    "parentName": "Detroit Tigers",
    "parentAbbrev": "DET"
  },
  "2134": {
    "name": "DSL Giants Black",
    "parentName": "San Francisco Giants",
    "parentAbbrev": "SF"
  },
  "2270": {
    "name": "DSL Cubs Red",
    "parentName": "Chicago Cubs",
    "parentAbbrev": "CHC"
  },
  "2310": {
    "name": "Reno Aces",
    "parentName": "Arizona Diamondbacks",
    "parentAbbrev": "AZ"
  },
  "2412": {
    "name": "DSL Rojos",
    "parentName": "Cincinnati Reds",
    "parentAbbrev": "CIN"
  },
  "2413": {
    "name": "DSL Rangers Red",
    "parentName": "Texas Rangers",
    "parentAbbrev": "TEX"
  },
  "2498": {
    "name": "Bowling Green Hot Rods",
    "parentName": "Tampa Bay Rays",
    "parentAbbrev": "TB"
  },
  "3130": {
    "name": "DSL Orioles Orange",
    "parentName": "Baltimore Orioles",
    "parentAbbrev": "BAL"
  },
  "3390": {
    "name": "Bradenton Marauders",
    "parentName": "Pittsburgh Pirates",
    "parentAbbrev": "PIT"
  },
  "3410": {
    "name": "Richmond Flying Squirrels",
    "parentName": "San Francisco Giants",
    "parentAbbrev": "SF"
  },
  "3430": {
    "name": "ACL Reds",
    "parentName": "Cincinnati Reds",
    "parentAbbrev": "CIN"
  },
  "3705": {
    "name": "Columbia Fireflies",
    "parentName": "Kansas City Royals",
    "parentAbbrev": "KC"
  },
  "3712": {
    "name": "Fayetteville Woodpeckers",
    "parentName": "Houston Astros",
    "parentAbbrev": "HOU"
  },
  "3898": {
    "name": "Wichita Wind Surge",
    "parentName": "Minnesota Twins",
    "parentAbbrev": "MIN"
  },
  "4124": {
    "name": "Pensacola Blue Wahoos",
    "parentName": "Miami Marlins",
    "parentAbbrev": "MIA"
  },
  "4404": {
    "name": "DSL Pirates Gold",
    "parentName": "Pittsburgh Pirates",
    "parentAbbrev": "PIT"
  },
  "4904": {
    "name": "El Paso Chihuahuas",
    "parentName": "San Diego Padres",
    "parentAbbrev": "SD"
  },
  "5005": {
    "name": "DSL Astros Orange",
    "parentName": "Houston Astros",
    "parentAbbrev": "HOU"
  },
  "5015": {
    "name": "Biloxi Shuckers",
    "parentName": "Milwaukee Brewers",
    "parentAbbrev": "MIL"
  },
  "5085": {
    "name": "DSL Phillies White",
    "parentName": "Philadelphia Phillies",
    "parentAbbrev": "PHI"
  },
  "5086": {
    "name": "DSL Tampa Bay",
    "parentName": "Tampa Bay Rays",
    "parentAbbrev": "TB"
  },
  "5087": {
    "name": "DSL Arizona Red",
    "parentName": "Arizona Diamondbacks",
    "parentAbbrev": "AZ"
  },
  "5368": {
    "name": "Amarillo Sod Poodles",
    "parentName": "Arizona Diamondbacks",
    "parentAbbrev": "AZ"
  },
  "5374": {
    "name": "ACL Guardians",
    "parentName": "Cleveland Guardians",
    "parentAbbrev": "CLE"
  },
  "5426": {
    "name": "ACL Athletics",
    "parentName": "Athletics",
    "parentAbbrev": "ATH"
  },
  "5427": {
    "name": "ACL Dodgers",
    "parentName": "Los Angeles Dodgers",
    "parentAbbrev": "LAD"
  },
  "5434": {
    "name": "Sugar Land Space Cowboys",
    "parentName": "Houston Astros",
    "parentAbbrev": "HOU"
  },
  "5506": {
    "name": "DSL CLE Goryl",
    "parentName": "Cleveland Guardians",
    "parentAbbrev": "CLE"
  },
  "6324": {
    "name": "Hub City Spartanburgers",
    "parentName": "Texas Rangers",
    "parentAbbrev": "TEX"
  },
  "6325": {
    "name": "Columbus Clingstones",
    "parentName": "Atlanta Braves",
    "parentAbbrev": "ATL"
  },
  "6482": {
    "name": "Ontario Tower Buzzers",
    "parentName": "Los Angeles Dodgers",
    "parentAbbrev": "LAD"
  }
};
